server:
  port: 8086

spring:
  application:
    name: Order_Service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true