# Server properties
server:
  port: 8086

# Spring properties
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online_food
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect



#  # Kafka properties
#  kafka:
#    template:
#      default-topic:
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.type.mapping=event:com.company.order_service.event.OrderRequestFood:

# Eureka properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true