server:
  port: 8085

spring:
  application:
    name: Online_Food_Service
  datasource:
    url: jdbc:postgresql://localhost:5432/online_food
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true